name: CI MLflow

on: 
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      #Checks-out your repository under $GITHUB WORKSPACE
      - uses: actions/checkout@v3

      #Setup Python 3.12.7
      - name: Set up Python 3.12.7
        uses: actions/setup-python@v4
        with:
          python-version: '3.12.7'
        
      #Check Env Variables
      - name: Check Env
        run: |
          echo $CSV_URL

      #Install mlflow
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install mlflow==2.19.0 dagshub==0.3.15 pandas scikit-learn matplotlib

      #Run as mlflow project
      - name: Run mlflow project
        env:
          MLFLOW_TRACKING_PASSWORD: ${{ secrets.DAGSHUB_TOKEN }}
        run: |
          #Mengkonfigurasi URI pelacakan otomatis leawt kode python
          python -c "import dagshub;, dagshub.init(repo_owner='ririhadis', repo_name='global_energy', mlflow=True)"

          #menjalankan mlflow secara lokal dengan URI yang sudah dikonfigurasi
          mlflow run MLProject --env-manager=local

      #Get latest run_id
      - name: Get latest MLflow run_id from DagsHub
        env: 
          MLFLOW_TRACKING_PASSWORD: ${{ secrets.DAGSHUB_TOKEN }}
        run: |
          #Mendapatkan kembali URI otomatis
          python -c "import dagshub;, dagshub.init(repo_owner='ririhadis', repo_name='global_energy', mlflow=True)"
          
          RUN_ID=$(python -c "
          import mlflow
          #Eksperimen default (ID: '0')
          runs = mlflow.search_runs(experiment_ids=['0'], order_by=['start_time DESC'], max_results=1)
          if not runs.empty:
            print(runs.iloc[0]['run_id'])
          ")
          echo "RUN_ID=$RUN_ID" >> $GITHUB_ENV
          echo "Latest run_id from DagsHub: $RUN_ID"

      - name: Install Google Drive dependencies
        run: |
          pip install --upgrade google-auth google-auth-oauthlib google-auth-httplib2 google-api-python-client

      - name: Upload to Google Drive
        env:
          GDRIVE_CREDENTIALS: ${{ secrets.GDRIVE_CREDENTIALS }}
          GDRIVE_FOLDER_ID: ${{ secrets.GDRIVE_FOLDER_ID }}
        run: |
          python MLproject/upload_to_gdrive.py

      #Build Docker Model
      - name : Build Docker Model
        env: 
          MLFLOW_TRACKING_PASSWORD: ${{ secrets.DAGSHUB_TOKEN }}
        run: |
          python -c "import dagshub; dagshub.init(repo_owner='ririhadis', repo_name='global_energy', mlflow=True)"
          mlflow models build-docker --model-uri "runs:/$RUN_ID/kmeans_model" --name "cc" --enable-mlserver

      #Login to Docker Hub
      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}

      #Tag the Docker Image
      - name : Tag Docker Image
        run: |
          docker tag cc ${{ secrets.DOCKER_HUB_USERNAME }}/cc:latest

      #Push Docker image to Docker Hub
      - name: Push Docker Image
        run: |
          docker push ${{ secrets.DOCKER_HUB_USERNAME }}/cc:latest
